### ISSUE TITLE
[CODE ISSUE] #1: IN FILE /commands/vacuumBegin.java

### ISSUE THREAD

**Issue by SticksDev** [bdentler/mechanicalmustang2019#2]
@bdentler 

Hello! I have noticed an issue with this file.

When `isFinished()` is called, it will return false. Shoud you put an if loop to get rid of `isFinished()`
Or maybye in an if loop.

Something like this

if vacMotor.setSpeed(0) {
  isFinished();
}
protected boolean isFinished() {
    return true;
    //some sort of exit command (or back to main script.)
}

Or if you want to get rid of isFinished();

if vacMotor.setSpeed(0) {
//exit command here
}

Cheers,
Tanner Sommers

**Comment by bdentler** [comment]
We will have isFinished return True so the vacuum runs until the robot stops when we are finished testing. This is just a way of turning off the motor after 10 seconds without the need to create a button to shut it off during testing.

Remember these commands are executed on the timing of the robot (approx. every 20 ms) so no need to create a loop. In fact, putting it in a loop is a bad thing because it won't have a chance to finish before it is called again.

**Comment by SticksDev** [comment]
Okay Thanks
